Minor fixes

diff --git a/etc/init b/etc/init
--- a/etc/init
+++ b/etc/init
@@ -9,12 +9,46 @@ unset BASH_ENV
 # Some distributions don't have /bin and /sbin in PATH anymore
 PATH="$PATH:/bin:/sbin:/usr/bin:/usr/sbin"
 
+# Backup $PATH to check commands
+PATH_BACKUP="$PATH"
+unset PATH
+
+# $SINGULARITY_IMAGE is not available in vanilla Singularity 2.2,
+# requires backporting a change that will be included in future release;
+# so, make very sure $SINGULARITY_IMAGE is defined
+if [ -z "${SINGULARITY_IMAGE+x}" ]; then
+    echo "ERROR: \$SINGULARITY_IMAGE is not defined" >&2
+    exit 1
+fi
+
+# UGent only allow images from user scratch directories
+# and VSC singularity group users.
+# $IMAGE_PATH will be empty if realpath is not able to find
+# $SINGULARITY_IMAGE in the file system.
+IMAGE_PATH="$(/usr/bin/realpath "$SINGULARITY_IMAGE" 2> /dev/null)"
+
+if [ -z "$IMAGE_PATH" ]; then
+    echo "ERROR: $SINGULARITY_IMAGE is not a valid image" >&2
+    exit 1
+fi
+
+if [[ $IMAGE_PATH =~ /vscmnt/.+_apps/.+|.+/user/(home|data)/.+ ]]; then
+    echo "ERROR: found not allowed path in $IMAGE_PATH" >&2
+    exit 1
+fi
+
+# Log user Singularity command for ELK
+/usr/bin/logger -t singularity "user=$USER image=$IMAGE_PATH jobid=${PBS_JOBID:-} cmd=$SINGULARITY_COMMAND"
+
+# Recover $PATH after command checks
+PATH="$PATH_BACKUP"
+
 # Don't save the shell's HISTFILE
 HISTFILE="/dev/null"
 
 # Set the timezone if it is not already set
 if [ -z "${TZ:-}" ]; then
-    TZ=`date +%Z`
+    TZ=$(/usr/bin/date +%Z)
 fi
 
 export PATH HISTFILE TZ
